/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a9DUVHwjzU2DmRycdJXBjB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsn6MxLo4ZW9Mx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: n6mxLo4zW9Mx/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsn6MxLo4ZW9Mx
});
